spring:
  datasource:
    url: jdbc:mysql://localhost:3306/apidesarrollo
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      # Para que Hibernate cree automáticamente las tablas.
      # En un entorno de producción se usaría 'none' o 'validate'.
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect